# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-17 04:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecipacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('quantidade_aulas', models.CharField(max_length=10)),
                ('data', models.DateField()),
                ('data_hora_inicio', models.TimeField(default=django.utils.timezone.now)),
                ('data_hora_fim', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_aulas', models.CharField(max_length=10)),
                ('data', models.DateField()),
                ('data_hora_inicio', models.TimeField(default=django.utils.timezone.now)),
                ('data_hora_fim', models.TimeField(default=django.utils.timezone.now)),
                ('data_limite_para_reposicao', models.DateField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisar.Curso', verbose_name='Curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplina_falta_set', to='sisar.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reposicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('quantidade_aulas', models.CharField(max_length=10)),
                ('data', models.DateField()),
                ('data_hora_inicio', models.TimeField(default=django.utils.timezone.now)),
                ('data_hora_fim', models.TimeField(default=django.utils.timezone.now)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisar.Curso', verbose_name='Curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplina_reposicao_set', to='sisar.Disciplina')),
                ('disciplina_substituida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplina_sustituida_reposicao_set', to='sisar.Disciplina')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisar.Modalidade', verbose_name='Modalidade')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_reposicao_set', to='sisar.Professor')),
                ('professor_substituido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_substituido_reposicao_set', to='sisar.Professor')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servidor_reposicao_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='reposicao',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisar.Turma', verbose_name='Turma'),
        ),
        migrations.AddField(
            model_name='falta',
            name='modalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisar.Modalidade', verbose_name='Modalidade'),
        ),
        migrations.AddField(
            model_name='falta',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_falta_set', to='sisar.Professor'),
        ),
        migrations.AddField(
            model_name='falta',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servidor_falta_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='falta',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisar.Turma', verbose_name='Turma'),
        ),
        migrations.AddField(
            model_name='antecipacao',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisar.Curso', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='antecipacao',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplina_antecipacao_set', to='sisar.Disciplina'),
        ),
        migrations.AddField(
            model_name='antecipacao',
            name='disciplina_substituida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplina_sustituida_antecipacao_set', to='sisar.Disciplina'),
        ),
        migrations.AddField(
            model_name='antecipacao',
            name='modalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisar.Modalidade', verbose_name='Modalidade'),
        ),
        migrations.AddField(
            model_name='antecipacao',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_antecipacao_set', to='sisar.Professor'),
        ),
        migrations.AddField(
            model_name='antecipacao',
            name='professor_substituido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_substituido_antecipacao_set', to='sisar.Professor'),
        ),
        migrations.AddField(
            model_name='antecipacao',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servidor_antecipacao_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='antecipacao',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisar.Turma', verbose_name='Turma'),
        ),
    ]
